---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yyju4g9j6ey3/public_html/
    
    # Root level files
    - /bin/cp Main/404.shtml $DEPLOYPATH
    - /bin/cp Main/config.php $DEPLOYPATH
    - /bin/cp Main/index.php $DEPLOYPATH
    
    # Deploy organized directories
    - /bin/cp -R Main/auth $DEPLOYPATH
    - /bin/cp -R Main/dashboards $DEPLOYPATH
    - /bin/cp -R Main/admin $DEPLOYPATH
    - /bin/cp -R Main/public $DEPLOYPATH
    - /bin/cp -R Main/modules $DEPLOYPATH
    - /bin/cp -R Main/partials $DEPLOYPATH
    - /bin/cp -R Main/assets $DEPLOYPATH
    - /bin/cp -R Main/uploads $DEPLOYPATH
    - /bin/cp -R Main/cgi-bin $DEPLOYPATH
    - /bin/cp -R Main/cron $DEPLOYPATH
    
    # Optional: Copy documentation (comment out if not needed in production)
    # - /bin/cp Main/WEB_ORGANIZATION_COMPLETE.md $DEPLOYPATH
    # - /bin/cp Main/QUICK_REFERENCE.md $DEPLOYPATH
