---
deployment:
  tasks:
    # ===================================
    # FAST DEPLOYMENT - Rsync only changed files from Main/
    # ===================================
    - export DEPLOYPATH=/home/yyju4g9j6ey3/public_html/
    
    # Core files (always update)
    - /bin/cp -f Main/config.php $DEPLOYPATH
    - /bin/cp -f Main/index.php $DEPLOYPATH
    - /bin/cp -f Main/404.shtml $DEPLOYPATH
    
    # Sync directories (only changed files) - MUCH FASTER!
    - /usr/bin/rsync -a --delete Main/auth/ $DEPLOYPATH/auth/
    - /usr/bin/rsync -a --delete Main/dashboards/ $DEPLOYPATH/dashboards/
    - /usr/bin/rsync -a --delete Main/admin/ $DEPLOYPATH/admin/
    - /usr/bin/rsync -a --delete Main/modules/ $DEPLOYPATH/modules/
    - /usr/bin/rsync -a --delete Main/partials/ $DEPLOYPATH/partials/
    - /usr/bin/rsync -a --delete Main/public/ $DEPLOYPATH/public/
    
    # Assets - sync without delete
    - /usr/bin/rsync -a Main/assets/ $DEPLOYPATH/assets/
    
    # Uploads - only add new, never delete or overwrite
    - /bin/mkdir -p $DEPLOYPATH/uploads/receipts
    - /bin/mkdir -p $DEPLOYPATH/uploads/rooms
    - /usr/bin/rsync -a --ignore-existing Main/uploads/ $DEPLOYPATH/uploads/ 2>/dev/null || true
    
    # Optional directories (only if they exist)
    - test -d Main/cgi-bin && /usr/bin/rsync -a Main/cgi-bin/ $DEPLOYPATH/cgi-bin/ || true
    - test -d Main/cron && /usr/bin/rsync -a Main/cron/ $DEPLOYPATH/cron/ || true
    
    # Set permissions efficiently
    - /bin/find $DEPLOYPATH/auth $DEPLOYPATH/dashboards $DEPLOYPATH/modules -type f -exec chmod 644 {} +
    - /bin/find $DEPLOYPATH/auth $DEPLOYPATH/dashboards $DEPLOYPATH/modules -type d -exec chmod 755 {} +
    - /bin/chmod -R 775 $DEPLOYPATH/uploads
    - /bin/chmod 644 $DEPLOYPATH/config.php $DEPLOYPATH/index.php
