
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yyju4g9j6ey3/public_html/
    - /bin/cp Main/index.php $DEPLOYPATH
    - /bin/cp Main/config.php $DEPLOYPATH
    - /bin/cp Main/login.php $DEPLOYPATH
