---
deployment:
  tasks:
    # ===================================
    # STEP 1: Clean up old files first
    # ===================================
    - export DEPLOYPATH=/home/yyju4g9j6ey3/public_html/
    
    # Remove old auth files from root
    - /bin/rm -f $DEPLOYPATH/login.php
    - /bin/rm -f $DEPLOYPATH/register.php
    - /bin/rm -f $DEPLOYPATH/register_admin.php
    - /bin/rm -f $DEPLOYPATH/logout.php
    - /bin/rm -f $DEPLOYPATH/auth.php
    
    # Remove old dashboard files from root
    - /bin/rm -f $DEPLOYPATH/dashboard.php
    - /bin/rm -f $DEPLOYPATH/student_dashboard.php
    - /bin/rm -f $DEPLOYPATH/owner_dashboard.php
    
    # Remove old admin files from root
    - /bin/rm -f $DEPLOYPATH/download_log.php
    - /bin/rm -f $DEPLOYPATH/test-pdo.php
    
    # Remove old public files from root
    - /bin/rm -f $DEPLOYPATH/index.html
    - /bin/rm -f $DEPLOYPATH/home.html
    - /bin/rm -f $DEPLOYPATH/layout-styles.css

    # ===================================
    # STEP 2: Deploy new organized structure
    # ===================================
    
    # Core files (root) - NO "Main/" prefix since we're IN Main/
    - /bin/cp config.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp 404.shtml $DEPLOYPATH

    # New organized directories - NO "Main/" prefix
    - /bin/cp -R auth $DEPLOYPATH
    - /bin/cp -R dashboards $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    
    # Existing directories (update) - NO "Main/" prefix
    - /bin/cp -R modules $DEPLOYPATH
    - /bin/cp -R partials $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R cgi-bin $DEPLOYPATH
    - /bin/cp -R cron $DEPLOYPATH
    
    # Uploads directory (preserve existing files)
    - /bin/mkdir -p $DEPLOYPATH/uploads
    - /bin/mkdir -p $DEPLOYPATH/uploads/receipts
    - /bin/mkdir -p $DEPLOYPATH/uploads/rooms
    - /bin/cp -n -R uploads/* $DEPLOYPATH/uploads/ 2>/dev/null || true
    
    # Set proper permissions
    - /bin/chmod -R 755 $DEPLOYPATH/auth
    - /bin/chmod -R 755 $DEPLOYPATH/dashboards
    - /bin/chmod -R 755 $DEPLOYPATH/admin
    - /bin/chmod -R 755 $DEPLOYPATH/modules
    - /bin/chmod -R 755 $DEPLOYPATH/partials
    - /bin/chmod -R 755 $DEPLOYPATH/public
    - /bin/chmod -R 775 $DEPLOYPATH/uploads
    - /bin/chmod 644 $DEPLOYPATH/config.php
    - /bin/chmod 644 $DEPLOYPATH/*.php
