---
deployment:
  tasks:
    # ===================================
    # FAST DEPLOYMENT - Rsync only changed files
    # ===================================
    - export DEPLOYPATH=/home/yyju4g9j6ey3/public_html/
    
    # Core files (always update these)
    - /bin/cp -f config.php $DEPLOYPATH
    - /bin/cp -f index.php $DEPLOYPATH
    
    # Sync directories (only changed files) - MUCH FASTER!
    - /usr/bin/rsync -a --delete auth/ $DEPLOYPATH/auth/
    - /usr/bin/rsync -a --delete dashboards/ $DEPLOYPATH/dashboards/
    - /usr/bin/rsync -a --delete admin/ $DEPLOYPATH/admin/
    - /usr/bin/rsync -a --delete modules/ $DEPLOYPATH/modules/
    - /usr/bin/rsync -a --delete partials/ $DEPLOYPATH/partials/
    - /usr/bin/rsync -a --delete public/ $DEPLOYPATH/public/
    # Shared helpers (mail.php) and vendor libs (PHPMailer)
    - /bin/mkdir -p $DEPLOYPATH/shared
    - /bin/mkdir -p $DEPLOYPATH/vendor
    - /usr/bin/rsync -a --delete shared/ $DEPLOYPATH/shared/
    - /usr/bin/rsync -a --delete vendor/ $DEPLOYPATH/vendor/
    
    # Assets - sync without delete (preserve uploaded files)
    - /usr/bin/rsync -a --exclude='uploads/*' assets/ $DEPLOYPATH/assets/
    
    # Uploads - only add new, never delete
    - /bin/mkdir -p $DEPLOYPATH/uploads/receipts
    - /bin/mkdir -p $DEPLOYPATH/uploads/rooms
    - /usr/bin/rsync -a --ignore-existing uploads/ $DEPLOYPATH/uploads/
    
    # Cron scripts
    - /usr/bin/rsync -a cron/ $DEPLOYPATH/cron/
    
    # Set permissions only on changed directories
    - /bin/find $DEPLOYPATH/auth -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH/auth -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH/dashboards -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH/dashboards -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH/modules -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH/modules -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH/shared -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH/shared -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH/vendor -type f -exec chmod 644 {} \; || true
    - /bin/find $DEPLOYPATH/vendor -type d -exec chmod 755 {} \; || true
    - /bin/chmod -R 775 $DEPLOYPATH/uploads

    # make sure target dirs exist
    - /bin/mkdir -p $DEPLOYPATH/shared
    - /bin/mkdir -p $DEPLOYPATH/vendor
    - /bin/mkdir -p $DEPLOYPATH/uploads/receipts
    - /bin/mkdir -p $DEPLOYPATH/uploads/rooms
